### ISSUE TITLE
Java Version.

### ISSUE THREAD

**Issue by VerveIsBad** [Martian-Mods/Martian-Alloys#4]
Java version is predefined in the gradle folder to be 11. 

`plugins {
	id 'fabric-loom' version '0.9-SNAPSHOT'
	id 'maven-publish'
}`

Please change to support the current version (16). @PaytonTheMartian

**Comment by VerveIsBad** [comment]
I would fix myself, but I'm not familiar with gradel.

**Comment by PaytonTheMartian** [comment]
The Java is set to 16, if it were 11 then MC wouldn't launch when I run `runClient`. The 11.6 in the `build.gradle` and `gradle.properties` refers to the loader version of Fabric. Which is 11.6 for MC 1.17.1 last I checked.

**Comment by VerveIsBad** [comment]
> The Java is set to 16, if it were 11 then MC wouldn't launch when I run `runClient`. The 11.6 in the `build.gradle` and `gradle.properties` refers to the loader version of Fabric. Which is 11.6 for MC 1.17.1 last I checked.

I Recieve two problems in the problems tab, 1 of witch refers to the code I pasted, saying that we are not using the latest version of java.
![Screenshot 2021-09-02 10 56 40 AM](https://user-images.githubusercontent.com/89467097/131873943-78a2137c-8b06-4715-88ea-1c2b17046124.png)

**Comment by PaytonTheMartian** [comment]
I think that has to do with Java 11 being installed on Gitpod by default.
Run the following command and see if anything changes:
`sdk install java 16.0.1.j9-adpt`

I'll try and make an auto-run script for Gitpod that'll run that for us.

**Comment by PaytonTheMartian** [comment]
Update: I see that problem. Though the output of `cat /home/gitpod/.sdkman/candidates/current/release` says that it's using Java 16. So I'm not sure what the problem is, maybe the problem doesn't get updated when we update the Java version.
I'll keep looking into this.

**Comment by VerveIsBad** [comment]
Alright. Its possible that one of our java support extensions is using a older version / we have to specify a specific one.

**Comment by PaytonTheMartian** [comment]
That's what I'm thinking. In the terminal Gradle works fine, but when I run a Gradle task from inside VSCode (<kbd>ctrl + shift + p</kbd>, then "Run a Gradle Build", then "build") gives an error.

**Comment by VerveIsBad** [comment]
What extension do you have running? Perhaps we need to use the same one/set a specific one for the mod.

**Comment by PaytonTheMartian** [comment]
I'm just using the default Java Language Extension, the full Java Extension Pack isn't available on Gitpod.

**Comment by VerveIsBad** [comment]
That is true, well it isn't a big idea, we can just run a update command
